services:
  - type: web
    name: smartseo
    env: docker
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true
    branch: main
